In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


In [3]:
df = pd.read_csv('try1.csv')

In [3]:
# df.dtypes
# df.replace("",np.nan,inplace=True)
# df.dropna(inplace=True)
len(df)

200825

In [4]:
# df.to_csv('try1.csv',mode='w',index=False)

200825

In [5]:
# df = df.head(15000)

df.tail()

symptom                           disease
200820        Increased sweating  Hypersecretion of growth hormone
200821  Menstrual irregularities  Hypersecretion of growth hormone
200822          Enlarged kidneys  Hypersecretion of growth hormone
200823           Bone overgrowth  Hypersecretion of growth hormone
200824             Enlarged lips  Hypersecretion of growth hormone

In [6]:
df = df.head(20000)

df.tail()

34528

In [7]:
symptom_list = list(df['symptom'].unique())
len(symptom_list)

8203

In [8]:
disease_list = list(df['disease'].unique())

len(disease_list)

18944

In [9]:
label_encoder = LabelEncoder()
encoded_values = label_encoder.fit_transform(symptom_list)
print(encoded_values)
len(encoded_values)

[12899  5141  9946 ... 14907  8742 28452]


34528

In [10]:
encoded_df = pd.DataFrame(columns = symptom_list)
encoded_df.head()

encoded_df.loc[0] = encoded_values

In [11]:
encoded_df

Holoprosencephaly  Cleft palate  Failed corpus callosum development  \
0              12899          5141                                9946   

   Cleft lips  Kidney anomalies  Low birth weight  Great vessel abnormalities  \
0        5133             15942             17742                       11793   

   Small jaw  Small facial features  Pigmented nevi  ...  High serum t3 level  \
0      28899                  28846           22679  ...                12721   

   Breast milk production in non-nursing women  Tall stature in children  \
0                                         3847                     30776   

   Excessive hair growth in women  Gigantism in children  \
0                            9346                  11659   

   Acromegaly in adults  Enlarged facial bones  \
0                  1597                   8706   

   Increasing space between teeth  Enlarged jaw bones  Skin odor  
0                           14907                8742      28452  

[1 rows x 34528 columns]

In [12]:
onehot_encoder = OneHotEncoder(sparse= False)
encoded_values = encoded_values.reshape(len(encoded_values), 1)
onehot_encoded = onehot_encoder.fit_transform(encoded_values) 

print(onehot_encoded)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
len(onehot_encoded)

34528

In [14]:
cols = np.asarray(symptom_list)
cols

array(['Holoprosencephaly', 'Cleft palate',
       'Failed corpus callosum development', ...,
       'Increasing space between teeth', 'Enlarged jaw bones',
       'Skin odor'], dtype='<U115')

In [15]:
onehot_df = pd.DataFrame(columns=cols)
onehot_df.head()

Empty DataFrame
Columns: [Holoprosencephaly, Cleft palate, Failed corpus callosum development, Cleft lips, Kidney anomalies, Low birth weight, Great vessel abnormalities, Small jaw, Small facial features, Pigmented nevi, Gray eyes, White hairs, Blue eyes, Myopia, Pink or reddish skin, Severe photophobia, Nystagmus, Progressive osteosclerosis, Mental retardation, Nausea, Dizziness, Palpitations, Mental changes, Rales, Chest pain, Tachycardia, Hypotension, Dyspnoea, Cramping pain in the abdomen, Abdominal discomfort, Abdominal swelling, Abdominal pain, Swelling of legs, Intestinal obstruction, Strong desire to eat salt or salty food, Can be a sign of adrenal problems, Flank discomfort, Palpable mass, Prolonged thrombin time, New hairs easily plucked, Thickening of skin on palms, Thickening of skin on soles, Skin shedding, Itching, Pain at base of thumb, Swelling at base of thumb, Difficulty gripping objects, Bruising at base of thumb, Hearing loss, Branchial fistulas, Partially developed mullerian structues - complete failure of gonad development, Partially developed wolffian structures - complete failure of gonad development, Streak gonads - complete failure of gonad development, Normal female external genitals - complete failure of gonad development, Normal mullerian structures - complete failure of gonad development, Ambiguous external genitals - partial failure of gonad development, Upper abdominal and back pain, Collapse, Light headedness, Pulsatile lump in abdomen, Confusion, Cold hands and feet, Sweating, Pale skin, Syncope, Excess urinary 5-oxoproline, Excess 5-oxoproline blood level, Abdominal bruising, Ruptured organs, Abdominal bleeding, Abnormal thrombin time, Excessive post-surgical bleeding, Hyperopia, Eye fatigue when using near vision, Blurry vision when using near vision, Presbyopia, Accommodative paralysis, High urine calcium level, Increased serum calcium level, Thrombosis, Inhibited clotting, Impaired memory, Dementia, Impaired consciousness, Headaches, Brain infarction, Brain hemorrhages, Low blood potassium level, Osteoporosis, Cysteine deposits in conjunctiva of eye, Cysteine deposits in cornea, Dwarfism, Renal tubular disease, Aminoaciduria, Developmental delay, Glucose in urine, Rickets, Fused eyelid margins, Small eyes, Easy bruising, ...]
Index: []

[0 rows x 34528 columns]

In [16]:
for i in range(len(onehot_encoded)):
    onehot_df.loc[i] = onehot_encoded[i]

KeyboardInterrupt: 

In [15]:
onehot_df

Holoprosencephaly  Cleft palate  Failed corpus callosum development  \
0                   0.0           0.0                                 0.0   
1                   0.0           0.0                                 0.0   
2                   0.0           0.0                                 0.0   
3                   0.0           0.0                                 0.0   
4                   0.0           0.0                                 0.0   
...                 ...           ...                                 ...   
6471                0.0           0.0                                 0.0   
6472                0.0           0.0                                 0.0   
6473                0.0           0.0                                 0.0   
6474                0.0           0.0                                 0.0   
6475                1.0           0.0                                 0.0   

      Cleft lips  Kidney anomalies  Low birth weight  \
0            0.0               0.0               0.0   
1            0.0               0.0               0.0   
2            0.0               0.0               0.0   
3            0.0               0.0               0.0   
4            0.0               0.0               0.0   
...          ...               ...               ...   
6471         0.0               0.0               0.0   
6472         0.0               0.0               0.0   
6473         0.0               0.0               0.0   
6474         0.0               0.0               0.0   
6475         0.0               0.0               0.0   

      Great vessel abnormalities  Small jaw  Small facial features  \
0                            0.0        0.0                    0.0   
1                            0.0        0.0                    0.0   
2                            0.0        0.0                    0.0   
3                            0.0        0.0                    0.0   
4                            0.0        0.0                    0.0   
...                          ...        ...                    ...   
6471                         0.0        0.0                    0.0   
6472                         0.0        0.0                    0.0   
6473                         0.0        0.0                    0.0   
6474                         0.0        0.0                    0.0   
6475                         0.0        0.0                    0.0   

      Pigmented nevi  ...  Absent limb heat sensitivity  \
0                0.0  ...                           0.0   
1                0.0  ...                           0.0   
2                0.0  ...                           0.0   
3                0.0  ...                           0.0   
4                0.0  ...                           0.0   
...              ...  ...                           ...   
6471             0.0  ...                           0.0   
6472             0.0  ...                           0.0   
6473             0.0  ...                           0.0   
6474             0.0  ...                           0.0   
6475             0.0  ...                           0.0   

      Atrophy of extremities  Mild vision problems  Absent limb reflexes  \
0                        0.0                   0.0                   0.0   
1                        0.0                   0.0                   0.0   
2                        0.0                   0.0                   0.0   
3                        0.0                   0.0                   0.0   
4                        0.0                   0.0                   0.0   
...                      ...                   ...                   ...   
6471                     0.0                   0.0                   0.0   
6472                     0.0                   0.0                   0.0   
6473                     0.0                   0.0                   0.0   
6474                     0.0                   0.0                   0.0   
6475                  

In [16]:
dis_df = df['disease']
dis_df.head()

0    Del (2) (p22-p21)
1    Del (2) (p22-p21)
2    Del (2) (p22-p21)
3    Del (2) (p22-p21)
4    Del (2) (p22-p21)
Name: disease, dtype: object

In [17]:
final_df = pd.concat([dis_df,onehot_df],axis=1)

final_df.head()


disease  Holoprosencephaly  Cleft palate  \
0  Del (2) (p22-p21)                0.0           0.0   
1  Del (2) (p22-p21)                0.0           0.0   
2  Del (2) (p22-p21)                0.0           0.0   
3  Del (2) (p22-p21)                0.0           0.0   
4  Del (2) (p22-p21)                0.0           0.0   

   Failed corpus callosum development  Cleft lips  Kidney anomalies  \
0                                 0.0         0.0               0.0   
1                                 0.0         0.0               0.0   
2                                 0.0         0.0               0.0   
3                                 0.0         0.0               0.0   
4                                 0.0         0.0               0.0   

   Low birth weight  Great vessel abnormalities  Small jaw  \
0               0.0                         0.0        0.0   
1               0.0                         0.0        0.0   
2               0.0                         0.0        0.0   
3               0.0                         0.0        0.0   
4               0.0                         0.0        0.0   

   Small facial features  ...  Absent limb heat sensitivity  \
0                    0.0  ...                           0.0   
1                    0.0  ...                           0.0   
2                    0.0  ...                           0.0   
3                    0.0  ...                           0.0   
4                    0.0  ...                           0.0   

   Atrophy of extremities  Mild vision problems  Absent limb reflexes  \
0                     0.0                   0.0                   0.0   
1                     0.0                   0.0                   0.0   
2                     0.0                   0.0                   0.0   
3                     0.0                   0.0                   0.0   
4                     0.0                   0.0                   0.0   

   Sensory lost in extremities  Hypertrophic neuropathy  \
0                          0.0                      0.0   
1                          0.0                      0.0   
2                          0.0                      0.0   
3                          0.0                      0.0   
4                          0.0                      0.0   

   Weakness in extremities  Incoordination of arms  \
0                      0.0                     0.0   
1                      0.0                     0.0   
2                      0.0                     0.0   
3                      0.0                     0.0   
4                      0.0                     0.0   

   Pain at tendon and ligament insertion sites  \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   'click' in hips when moved in certain ways  
0                                         0.0  
1                                         0.0  
2                                         0.0  
3                                         0.0  
4                                         0.0  

[5 rows x 6477 columns]

In [18]:
final_df = pd.concat([dis_df,onehot_df],axis=1)

final_df.head()


In [20]:
final_df.drop_duplicates(keep='first',inplace=True)

final_df.head()

disease  Holoprosencephaly  Cleft palate  \
0  Del (2) (p22-p21)                0.0           0.0   
1  Del (2) (p22-p21)                0.0           0.0   
2  Del (2) (p22-p21)                0.0           0.0   
3  Del (2) (p22-p21)                0.0           0.0   
4  Del (2) (p22-p21)                0.0           0.0   

   Failed corpus callosum development  Cleft lips  Kidney anomalies  \
0                                 0.0         0.0               0.0   
1                                 0.0         0.0               0.0   
2                                 0.0         0.0               0.0   
3                                 0.0         0.0               0.0   
4                                 0.0         0.0               0.0   

   Low birth weight  Great vessel abnormalities  Small jaw  \
0               0.0                         0.0        0.0   
1               0.0                         0.0        0.0   
2               0.0                         0.0        0.0   
3               0.0                         0.0        0.0   
4               0.0                         0.0        0.0   

   Small facial features  ...  Long hands  Sexual interest in being tied up  \
0                    0.0  ...         0.0                               0.0   
1                    0.0  ...         0.0                               0.0   
2                    0.0  ...         0.0                               0.0   
3                    0.0  ...         0.0                               0.0   
4                    0.0  ...         0.0                               0.0   

   Sexual preference for being tied up  \
0                                  0.0   
1                                  0.0   
2                                  0.0   
3                                  0.0   
4                                  0.0   

   Recurring intense sexual fantasies involving being tied up  \
0                                                0.0            
1                                                0.0            
2                                                0.0            
3                                                0.0            
4                                                0.0            

   Impaired alertness  Swollen abdominal lymph nodes  Viral infections  \
0                 0.0                            0.0               0.0   
1                 0.0                            0.0               0.0   
2                 0.0                            0.0               0.0   
3                 0.0                            0.0               0.0   
4                 0.0                            0.0               0.0   

   Compressed duodenum  Increased white blood cell count  Dry throat  
0                  0.0                               0.0         0.0  
1                  0.0                               0.0         0.0  
2                  0.0                               0.0         0.0  
3                  0.0                               0.0         0.0  
4                  0.0                               0.0         0.0  

[5 rows x 8204 columns]

In [ ]:
final_df = final_df.groupby('disease').sum()
final_df = final_df.reset_index()


In [ ]:
final_df.to_csv('test_train.csv',mode='w',index=False)

In [ ]:
X = final_df[cols]
Y = final_df['disease']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=10)

In [ ]:
# classifier = DecisionTreeClassifier()
classifier = RandomForestClassifier(n_estimators=100)
cl_dt = classifier.fit(x_train,y_train)

In [ ]:
cl_dt.score(x_train,y_train)

0.4333118556701031

In [ ]:
dis_pred = cl_dt.predict(x_test)

In [ ]:
dis_real = y_test.values