In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import matplotlib.pyplot as plt 
%matplotlib inline
import csv

In [2]:
df = pd.read_csv('new_set.csv')

In [3]:
df

symptom                           disease
0                        Holoprosencephaly                 Del (2) (p22-p21)
1                             Cleft palate                 Del (2) (p22-p21)
2       Failed corpus callosum development                 Del (2) (p22-p21)
3                               Cleft lips                 Del (2) (p22-p21)
4                         Kidney anomalies                 Del (2) (p22-p21)
...                                    ...                               ...
200864                  Increased sweating  Hypersecretion of growth hormone
200865            Menstrual irregularities  Hypersecretion of growth hormone
200866                    Enlarged kidneys  Hypersecretion of growth hormone
200867                     Bone overgrowth  Hypersecretion of growth hormone
200868                       Enlarged lips  Hypersecretion of growth hormone

[200869 rows x 2 columns]

In [4]:
df.replace(float('nan'), np.nan, inplace=True)
df.dropna(inplace=True)

In [5]:
disease_list = list(df['disease'].unique())

In [6]:
len(disease_list)

18944

In [7]:
symptom_list = list(df['symptom'].unique())
len(symptom_list)

34528

In [8]:
from collections import defaultdict
disease_sym = defaultdict(list)

k = 0
for i in df['disease'].values:
    disease_sym[i].append(df.iloc[k]['symptom'])
    k += 1

In [9]:
disease_sym

defaultdict(list,
            {'Del (2) (p22-p21)': ['Holoprosencephaly',
              'Cleft palate',
              'Failed corpus callosum development',
              'Cleft lips',
              'Kidney anomalies'],
             '2q22-q24 deletion': ['Low birth weight',
              'Cleft palate',
              'Great vessel abnormalities',
              'Small jaw',
              'Small facial features'],
             'Ablinism i syndrome': ['Pigmented nevi',
              'Gray eyes',
              'White hairs',
              'Blue eyes',
              'Myopia',
              'Pink or reddish skin',
              'Severe photophobia',
              'Nystagmus'],
             'Hunter-macpherson syndrome': ['Progressive osteosclerosis',
              'Mental retardation'],
             'Ventricular familial preexcitation syndrome': ['Nausea',
              'Dizziness',
              'Palpitations',
              'Mental changes',
              'Rales',
              'Chest pain',

In [10]:
df.dtypes

symptom    object
disease    object
dtype: object

In [11]:
label_encoder = LabelEncoder()
encoded_values2 = label_encoder.fit_transform(df['symptom'])
print(encoded_values2)
len(encoded_values2)

[12899  5141  9946 ...  8747  3570  8757]


200825

In [12]:
encoded_values = label_encoder.fit_transform(symptom_list)
print(encoded_values)
len(encoded_values)

[12899  5141  9946 ... 14907  8742 28452]


34528

In [13]:
encoded_df = pd.DataFrame(columns = symptom_list)
encoded_df.head()

encoded_df.loc[0] = encoded_values

In [14]:
encoded_df

Holoprosencephaly Cleft palate Failed corpus callosum development  \
0             12899         5141                               9946   

  Cleft lips Kidney anomalies Low birth weight Great vessel abnormalities  \
0       5133            15942            17742                      11793   

  Small jaw Small facial features Pigmented nevi  ... High serum t3 level  \
0     28899                 28846          22679  ...               12721   

  Breast milk production in non-nursing women Tall stature in children  \
0                                        3847                    30776   

  Excessive hair growth in women Gigantism in children Acromegaly in adults  \
0                           9346                 11659                 1597   

  Enlarged facial bones Increasing space between teeth Enlarged jaw bones  \
0                  8706                          14907               8742   

  Skin odor  
0     28452  

[1 rows x 34528 columns]

In [15]:
onehot_encoder = OneHotEncoder(sparse= False)
encoded_values = encoded_values.reshape(len(encoded_values), 1)
onehot_encoded = onehot_encoder.fit_transform(encoded_values) 

print(onehot_encoded)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [16]:
onehot_encoded[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [17]:
len(onehot_encoded[0])

34528

In [18]:
cols = np.asarray(symptom_list)
cols

array(['Holoprosencephaly', 'Cleft palate',
       'Failed corpus callosum development', ...,
       'Increasing space between teeth', 'Enlarged jaw bones',
       'Skin odor'], dtype='<U115')

In [19]:
len(cols)

34528

In [26]:
onehot_df = pd.DataFrame(columns=cols)
onehot_df.head()

Empty DataFrame
Columns: [Holoprosencephaly, Cleft palate, Failed corpus callosum development, Cleft lips, Kidney anomalies, Low birth weight, Great vessel abnormalities, Small jaw, Small facial features, Pigmented nevi, Gray eyes, White hairs, Blue eyes, Myopia, Pink or reddish skin, Severe photophobia, Nystagmus, Progressive osteosclerosis, Mental retardation, Nausea, Dizziness, Palpitations, Mental changes, Rales, Chest pain, Tachycardia, Hypotension, Dyspnoea, Cramping pain in the abdomen, Abdominal discomfort, Abdominal swelling, Abdominal pain, Swelling of legs, Intestinal obstruction, Strong desire to eat salt or salty food, Can be a sign of adrenal problems, Flank discomfort, Palpable mass, Prolonged thrombin time, New hairs easily plucked, Thickening of skin on palms, Thickening of skin on soles, Skin shedding, Itching, Pain at base of thumb, Swelling at base of thumb, Difficulty gripping objects, Bruising at base of thumb, Hearing loss, Branchial fistulas, Partially developed mullerian structues - complete failure of gonad development, Partially developed wolffian structures - complete failure of gonad development, Streak gonads - complete failure of gonad development, Normal female external genitals - complete failure of gonad development, Normal mullerian structures - complete failure of gonad development, Ambiguous external genitals - partial failure of gonad development, Upper abdominal and back pain, Collapse, Light headedness, Pulsatile lump in abdomen, Confusion, Cold hands and feet, Sweating, Pale skin, Syncope, Excess urinary 5-oxoproline, Excess 5-oxoproline blood level, Abdominal bruising, Ruptured organs, Abdominal bleeding, Abnormal thrombin time, Excessive post-surgical bleeding, Hyperopia, Eye fatigue when using near vision, Blurry vision when using near vision, Presbyopia, Accommodative paralysis, High urine calcium level, Increased serum calcium level, Thrombosis, Inhibited clotting, Impaired memory, Dementia, Impaired consciousness, Headaches, Brain infarction, Brain hemorrhages, Low blood potassium level, Osteoporosis, Cysteine deposits in conjunctiva of eye, Cysteine deposits in cornea, Dwarfism, Renal tubular disease, Aminoaciduria, Developmental delay, Glucose in urine, Rickets, Fused eyelid margins, Small eyes, Easy bruising, ...]
Index: []

[0 rows x 34528 columns]

In [27]:
for i in range(len(onehot_encoded)):
    onehot_df.loc[i] = onehot_encoded[i]
    # print(onehot_df.loc[i])

KeyboardInterrupt: 